Parameters:
  ApplicationName:
    Type: String
    Description: The name of the application 
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The id of the VPC for the security group

Resources:
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub The security group for ${ApplicationName}
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: '10.0.0.0/25'
          Description: SSH access for Engineering department
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: '192.168.0.0/25'
          Description: SSH access for HR department
      VpcId: !Ref VpcId

Outputs:
  SSHGroupId:
    Value: !Ref SSHSecurityGroup
    Description: Id for the SSH security group
