Parameters:
  InstanceType:
    Type: String
    Description: EC2 instance type
    Default: t2.nano
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
    ConstraintDescription: Only t2.nano, t2.micro or t2.small instance types are allowed
  
  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    ConstraintDescription: Must be either dev or prod

Rules:
  ProdInstanceType:
    RuleCondition: !Equals [!Ref Environment, prod]
    Assertions:
      - Assert: !Equals [!Ref InstanceType, t2.small]
        AssertDescription: For prod environment, the instance type must be t2.small
    
  DevInstanceType:
    RuleCondition: !Equals [!Ref Environment, dev]
    Assertions:
      - Assert: 
          'Fn::Or':
            - !Equals [!Ref InstanceType, t2.nano]
            - !Equals [!Ref InstanceType, t2.micro]
        AssertDescription: For dev environment, the instance type must be either t2.nano or t2.micro

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
